### ISSUE TITLE
CRITICAL  BUG: Editing a task locks up all user input!

### ISSUE THREAD

**Issue by paulpreibisch** [zagortenay333/timepp#201] opened 2022-07-28 17:39 UTC
CRITICAL  BUG:
Editing a task locks up all user input!
I can move the mouse, but can not click on anything.
Only remedy is to reboot!
Note: Using latest version of popOs 22.04

To Reproduce
Go to tasks
click on pencil icon of a task

![image](https://user-images.githubusercontent.com/19810611/181613277-ed3a8a4d-3e36-471d-9f70-8e2b72cb1f41.png)

**Comment by landegt** [comment] 2022-07-28 23:00
While this definitely isn't a fix, as a temporary Tipp instead of rebooting you should be able to press 'alt' 'f2' and then enter 'r'. This will restart gnome-shell

**Comment by paulpreibisch** [comment] 2022-07-29 00:04
I tried that, but I still was not able to regain control, had to reboot.  By the way, I love this extension  - so for now, I will fork and remove the button, or just remember not to press it. 
![image](https://user-images.githubusercontent.com/19810611/181656699-1146ebc8-c65a-49e3-b14c-445e4921ba12.png)

**Comment by c-git** [comment] 2022-07-30 16:29
What version of gnome does that OS use?

**Comment by paulpreibisch** [comment] 2022-07-30 19:44
I am using PopOs 22.04 and I have GNOME Shell 42.2 installed

**Comment by mdunc** [comment] 2022-08-10 16:01
Exact same issue here - also on Pop_OS 22.04.  Gnome Shell appears to completely freeze, but there's at least some response to mouseover on elements on the right of the Time++ UI when editing a task.  Clicking does nothing though and alt-f2 doesn't show the run dialog or anything.  Cannot use any trackpad gestures or keyboard shortcuts to interact with the desktop at all.

**Comment by juanxrv** [comment] 2022-08-15 07:30
Same issue on Arch Linux

**Comment by MathieuDR** [comment] 2022-08-20 15:56
Same issue on, also on Pop_OS 22.04. Locking my PC and then login in again resolves it, IIRC.

**Comment by JuanferM** [comment] 2022-09-07 06:22
To regain control I did Ctrl+Alt+F1 then suspended the computer on Ubuntu 22.04. After login again the extension was successfully closed.

The culprit of the issue is the code in the file `view__task_editor.js` in the `sections/todo/` directory. Lines 210 to 215 lock up the task editor. After commenting out these lines I regained control of the editor and everything seems to work just fine.

Here is a screenshot of the changes made.

![Screenshot from 2022-09-07 08-21-07](https://user-images.githubusercontent.com/56729053/188803600-ae8dd560-c73b-465b-a910-9a8870368844.png)

**EDIT**: Commenting line 214 only (`return Clutter.EVENT_STOP`) seems to do the trick (I would recommend this approach since it keeps the most functionality).

**EDIT 2**: After restarting, Ubuntu freezed up, figured it could be because of the modifications so I erased the extension's directory. Commenting line 214 helps when trying to edit a task but leaving that line commented is also problematic when restarting on Ubuntu 22.04.

**Comment by hazemk537** [comment] 2022-09-11 12:56
double right click on task --- solved for me

**Comment by psydvl** [comment] 2022-09-18 14:55
I think, related issue for GNOME Shell
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5882

**Comment by Yannik** [comment] 2022-09-18 15:49
Can confirm the issue on fedora 36 with gnome 42

**Comment by landegt** [comment] 2022-09-22 20:55
Just opened PR #208 with a fix for this issue.
Please check it out and comment on the PR if it works for you, that way it can be merged more quickly.

**Comment by rcsm17** [comment] 2022-10-25 10:49
I switched to the other user and killed gnome-shell process for the previous user. This restarted gnome-shell for the user with the "locked input" .

**Comment by zagortenay333** [comment] 2023-06-01 11:49
Fixed.

**Closed as completed by zagortenay333** 2023-06-01 11:49 UTC
